"""
utils/pdf_export.py — Generates a downloadable PDF legal report.

═══════════════════════════════════════════════════════════════
  WHERE THIS IS CALLED
═══════════════════════════════════════════════════════════════

  Called from: routers/conversations.py → export_conversation_pdf()
  Triggered by: GET /conversations/{id}/export-pdf
  Frontend: ExportButton.tsx triggers download via fetch()

═══════════════════════════════════════════════════════════════
  WHAT THE PDF SHOULD CONTAIN (in order)
═══════════════════════════════════════════════════════════════

  1. Header
       - "LexAI Legal Case Analysis" title
       - Generated date + username
       - Disclaimer: "This is not legal advice..."

  2. Case Summary  ← from conversation.intake_summary (dict)
       - Incident description
       - Location and state
       - Perpetrator
       - Written proof available
       - Date of incident

  3. Case Strength Score  ← from conversation.research_result["case_strength_score"]
       - Large number: "74 / 100"
       - Text label: "Strong" / "Moderate" / "Weak" based on range
       - (PDF can't do animated bars — use a filled rectangle instead)

  4. Legal Analysis  ← from conversation.research_result["opinion"]
       - Full markdown text (convert to plain text or use reportlab Paragraph)

  5. Recommended Next Steps  ← from conversation.research_result["recommended_actions"]
       - Numbered list

  6. Recommended Attorneys  ← from conversation.research_result["referred_lawyers"]
       - Name, address, specialty, rating per lawyer

  7. Footer on every page
       - "This report was generated by LexAI. Not a substitute for legal counsel."

═══════════════════════════════════════════════════════════════
  HOW TO IMPLEMENT (two options)
═══════════════════════════════════════════════════════════════

  OPTION A — reportlab (pure Python, no browser needed):
    from reportlab.lib.pagesizes import letter
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
    from reportlab.lib.styles import getSampleStyleSheet
    from io import BytesIO

    def generate_pdf(conversation) -> bytes:
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        story = []
        # ... build story list with Paragraphs ...
        doc.build(story)
        return buffer.getvalue()

  OPTION B — weasyprint (renders HTML → PDF, easier to style):
    from weasyprint import HTML

    def generate_pdf(conversation) -> bytes:
        html_content = build_html(conversation)  # write an HTML template
        return HTML(string=html_content).write_pdf()

  RECOMMENDATION: Use weasyprint if the team knows HTML/CSS.
    It's much easier to make it look polished (just write HTML).
    Already declared as an optional extra — install with: uv sync --extra pdf-html

═══════════════════════════════════════════════════════════════
  FUNCTION SIGNATURE (do not change — called from conversations.py)
═══════════════════════════════════════════════════════════════

  def generate_pdf(conversation) -> bytes:
      # conversation is a Conversation ORM object (models/models.py)
      # conversation.intake_summary   → dict (case info)
      # conversation.research_result  → dict (opinion, score, actions, lawyers)
      # conversation.title             → str
      # conversation.created_at        → datetime
      # Returns: raw PDF bytes
"""

from datetime import datetime
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

# ── Colour palette ────────────────────────────────────────────────────────────
_DARK_BLUE = colors.HexColor("#1e3a5f")
_MID_BLUE = colors.HexColor("#2563eb")
_LIGHT_GRAY = colors.HexColor("#f1f5f9")
_GREEN = colors.HexColor("#15803d")
_AMBER = colors.HexColor("#b45309")
_RED = colors.HexColor("#b91c1c")
_TEXT = colors.HexColor("#1e293b")


def _score_color(score: int) -> colors.HexColor:
    if score >= 86:
        return _GREEN
    if score >= 61:
        return colors.HexColor("#22c55e")
    if score >= 31:
        return _AMBER
    return _RED


def _score_label(score: int) -> str:
    if score >= 86:
        return "Very Strong"
    if score >= 61:
        return "Strong"
    if score >= 31:
        return "Moderate"
    return "Weak"


def _build_styles() -> dict:
    """Return a dict of named ParagraphStyles used throughout the PDF."""
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "title",
            parent=base["Title"],
            fontSize=22,
            textColor=_DARK_BLUE,
            spaceAfter=4,
        ),
        "subtitle": ParagraphStyle(
            "subtitle",
            parent=base["Normal"],
            fontSize=10,
            textColor=colors.HexColor("#64748b"),
            spaceAfter=2,
        ),
        "section": ParagraphStyle(
            "section",
            parent=base["Heading2"],
            fontSize=13,
            textColor=_DARK_BLUE,
            spaceBefore=14,
            spaceAfter=4,
            borderPad=2,
        ),
        "body": ParagraphStyle(
            "body",
            parent=base["Normal"],
            fontSize=10,
            textColor=_TEXT,
            leading=15,
            spaceAfter=4,
        ),
        "label": ParagraphStyle(
            "label",
            parent=base["Normal"],
            fontSize=9,
            textColor=colors.HexColor("#64748b"),
        ),
        "value": ParagraphStyle(
            "value",
            parent=base["Normal"],
            fontSize=10,
            textColor=_TEXT,
            leading=14,
        ),
        "disclaimer": ParagraphStyle(
            "disclaimer",
            parent=base["Normal"],
            fontSize=8,
            textColor=colors.HexColor("#94a3b8"),
            leading=11,
        ),
        "bullet": ParagraphStyle(
            "bullet",
            parent=base["Normal"],
            fontSize=10,
            textColor=_TEXT,
            leading=15,
            leftIndent=14,
            spaceAfter=2,
        ),
    }


def _add_header(story: list, conversation, styles: dict) -> None:
    """Page 1 header: app name, report title, generated date, disclaimer strip."""
    story.append(Paragraph("LexAI", styles["title"]))
    story.append(Paragraph("Legal Case Analysis Report", styles["subtitle"]))
    story.append(
        Paragraph(
            f"Generated: {datetime.utcnow().strftime('%B %d, %Y at %H:%M UTC')}",
            styles["subtitle"],
        )
    )
    story.append(Spacer(1, 6))
    story.append(HRFlowable(width="100%", thickness=2, color=_DARK_BLUE))
    story.append(Spacer(1, 4))
    # Prominent disclaimer — legal requirement
    story.append(
        Paragraph(
            "<b>⚠ DISCLAIMER:</b> This report is generated by an AI system and is provided for "
            "informational purposes only. It does not constitute legal advice. "
            "Always consult a licensed attorney before taking legal action.",
            styles["disclaimer"],
        )
    )
    story.append(Spacer(1, 10))


def _add_case_summary(story: list, intake: dict, styles: dict) -> None:
    """Section 1: structured case details from intake_summary."""
    story.append(Paragraph("1. Case Summary", styles["section"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=_LIGHT_GRAY))
    story.append(Spacer(1, 6))

    fields = [
        ("Incident Description", intake.get("incident", "—")),
        ("Location", intake.get("location", "—")),
        ("State", intake.get("state", "—")),
        ("Perpetrator / Respondent", intake.get("perpetrator", "—")),
        ("Written Proof Available", intake.get("written_proof", "—")),
        ("Date of Incident", intake.get("date_of_incident", "—")),
    ]

    table_data = [
        [
            Paragraph(label, styles["label"]),
            Paragraph(str(value), styles["value"]),
        ]
        for label, value in fields
    ]

    tbl = Table(table_data, colWidths=[1.8 * inch, 5.2 * inch])
    tbl.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, _LIGHT_GRAY]),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    story.append(tbl)


def _add_score(story: list, score: int, styles: dict) -> None:
    """Section 2: Case Strength Score with colour-coded bar and label."""
    story.append(Paragraph("2. Case Strength Score", styles["section"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=_LIGHT_GRAY))
    story.append(Spacer(1, 8))

    label = _score_label(score)
    colour = _score_color(score)

    # Score number + label
    score_style = ParagraphStyle(
        "score_num",
        fontSize=32,
        textColor=colour,
        leading=38,
    )
    story.append(Paragraph(f"<b>{score} / 100</b> — {label}", score_style))
    story.append(Spacer(1, 6))

    # Visual bar: filled rectangle proportional to score
    bar_width = 6.0 * inch
    filled = bar_width * (score / 100)

    bar_data = [["", ""]]  # dummy table used purely for coloured cells
    bar = Table(
        bar_data,
        colWidths=[filled, bar_width - filled],
        rowHeights=[14],
    )
    bar.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, 0), colour),
                ("BACKGROUND", (1, 0), (1, 0), _LIGHT_GRAY),
                ("LINEABOVE", (0, 0), (-1, -1), 0.5, colors.white),
            ]
        )
    )
    story.append(bar)
    story.append(Spacer(1, 4))

    score_ranges = [
        ("0–30", "Weak — limited legal basis found", _RED),
        ("31–60", "Moderate — some merit, challenges exist", _AMBER),
        ("61–85", "Strong — clear legal violations identified", _GREEN),
        ("86–100", "Very Strong — excellent precedent and law support", colors.HexColor("#15803d")),
    ]
    for rng, desc, c in score_ranges:
        marker = "▶ " if _score_label(score) == desc.split(" —")[0].strip() else "   "
        story.append(
            Paragraph(
                f'<font color="#{c.hexval()[1:]}">{marker}{rng}: {desc}</font>',
                styles["disclaimer"],
            )
        )
    story.append(Spacer(1, 6))


def _add_opinion(story: list, opinion: str, styles: dict) -> None:
    """Section 3: full legal analysis text from opinion_agent."""
    story.append(Paragraph("3. Legal Analysis", styles["section"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=_LIGHT_GRAY))
    story.append(Spacer(1, 6))
    # Strip basic markdown bold/italic — reportlab doesn't render markdown
    clean = (
        opinion.replace("**", "<b>", 1)
        .replace("**", "</b>", 1)
        .replace("*", "")
        .replace("##", "")
        .replace("#", "")
        .replace("\n\n", "<br/><br/>")
        .replace("\n", "<br/>")
    )
    story.append(Paragraph(clean, styles["body"]))


def _add_actions(story: list, actions: list[str], styles: dict) -> None:
    """Section 4: recommended next steps as a numbered list."""
    story.append(Paragraph("4. Recommended Next Steps", styles["section"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=_LIGHT_GRAY))
    story.append(Spacer(1, 6))
    for i, action in enumerate(actions, 1):
        story.append(Paragraph(f"{i}. {action}", styles["bullet"]))
    if not actions:
        story.append(Paragraph("No specific actions identified.", styles["body"]))


def _add_lawyers(story: list, lawyers: list[dict], styles: dict) -> None:
    """Section 5: referred attorneys table."""
    story.append(Paragraph("5. Recommended Attorneys", styles["section"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=_LIGHT_GRAY))
    story.append(Spacer(1, 6))

    if not lawyers:
        story.append(Paragraph("No attorney referrals available.", styles["body"]))
        return

    header = [
        Paragraph("<b>Name</b>", styles["label"]),
        Paragraph("<b>Address</b>", styles["label"]),
        Paragraph("<b>Specialty</b>", styles["label"]),
        Paragraph("<b>Rating</b>", styles["label"]),
    ]
    rows = [header]
    for lw in lawyers[:6]:  # max 6 lawyers in PDF
        rows.append(
            [
                Paragraph(lw.get("name", "—"), styles["value"]),
                Paragraph(lw.get("address", "—"), styles["value"]),
                Paragraph(lw.get("specialty", "—"), styles["value"]),
                Paragraph(str(lw.get("rating", "—")), styles["value"]),
            ]
        )

    tbl = Table(rows, colWidths=[1.8 * inch, 2.2 * inch, 1.4 * inch, 0.7 * inch])
    tbl.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), _DARK_BLUE),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, _LIGHT_GRAY]),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#e2e8f0")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    story.append(tbl)


def _footer_canvas(canvas, doc):
    """
    ReportLab canvas callback — draws a footer on every page.
    Called automatically by SimpleDocTemplate during build().
    """
    canvas.saveState()
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(colors.HexColor("#94a3b8"))
    footer_text = (
        "This report was generated by LexAI and is not a substitute for professional legal counsel. "
        f"Page {doc.page}"
    )
    canvas.drawCentredString(letter[0] / 2, 0.4 * inch, footer_text)
    canvas.restoreState()


def generate_pdf(conversation) -> bytes:
    """
    Generate a professional PDF legal report for a completed conversation.

    Args:
        conversation: Conversation ORM object (models/models.py).
                      conversation.intake_summary   → dict  (case info from intake agent)
                      conversation.research_result  → dict  (opinion, score, actions, lawyers)
                      conversation.title             → str   (auto-generated sidebar title)
                      conversation.created_at        → datetime

    Returns:
        bytes: Raw PDF content. FastAPI returns this directly with
               media_type="application/pdf" in conversations.py.

    Called by:
        routers/conversations.py → export_conversation_pdf()
        Endpoint: GET /conversations/{id}/export-pdf
    """
    intake: dict = conversation.intake_summary or {}
    research: dict = conversation.research_result or {}

    score: int = research.get("case_strength_score", 0)
    opinion: str = research.get("opinion", "Analysis not yet available.")
    actions: list[str] = research.get("recommended_actions", [])
    lawyers: list[dict] = research.get("referred_lawyers", [])

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )

    styles = _build_styles()
    story: list = []

    _add_header(story, conversation, styles)
    _add_case_summary(story, intake, styles)
    _add_score(story, score, styles)
    _add_opinion(story, opinion, styles)
    _add_actions(story, actions, styles)
    _add_lawyers(story, lawyers, styles)

    # Final disclaimer paragraph
    story.append(Spacer(1, 16))
    story.append(HRFlowable(width="100%", thickness=1, color=_LIGHT_GRAY))
    story.append(Spacer(1, 4))
    story.append(
        Paragraph(
            "LexAI is an AI-assisted legal research tool. This report is for informational "
            "purposes only and does not establish an attorney-client relationship. The laws "
            "referenced may have changed. Always verify information with a licensed attorney "
            "before taking any legal action.",
            styles["disclaimer"],
        )
    )

    doc.build(story, onFirstPage=_footer_canvas, onLaterPages=_footer_canvas)
    return buffer.getvalue()
