"""
utils/pdf_export.py — Generates a downloadable PDF legal report.

═══════════════════════════════════════════════════════════════
  WHERE THIS IS CALLED
═══════════════════════════════════════════════════════════════

  Called from: routers/conversations.py → export_conversation_pdf()
  Triggered by: GET /conversations/{id}/export-pdf
  Frontend: ExportButton.tsx triggers download via fetch()

═══════════════════════════════════════════════════════════════
  WHAT THE PDF SHOULD CONTAIN (in order)
═══════════════════════════════════════════════════════════════

  1. Header
       - "LexAI Legal Case Analysis" title
       - Generated date + username
       - Disclaimer: "This is not legal advice..."

  2. Case Summary  ← from conversation.intake_summary (dict)
       - Incident description
       - Location and state
       - Perpetrator
       - Written proof available
       - Date of incident

  3. Case Strength Score  ← from conversation.research_result["case_strength_score"]
       - Large number: "74 / 100"
       - Text label: "Strong" / "Moderate" / "Weak" based on range
       - (PDF can't do animated bars — use a filled rectangle instead)

  4. Legal Analysis  ← from conversation.research_result["opinion"]
       - Full markdown text (convert to plain text or use reportlab Paragraph)

  5. Recommended Next Steps  ← from conversation.research_result["recommended_actions"]
       - Numbered list

  6. Recommended Attorneys  ← from conversation.research_result["referred_lawyers"]
       - Name, address, specialty, rating per lawyer

  7. Footer on every page
       - "This report was generated by LexAI. Not a substitute for legal counsel."

═══════════════════════════════════════════════════════════════
  HOW TO IMPLEMENT (two options)
═══════════════════════════════════════════════════════════════

  OPTION A — reportlab (pure Python, no browser needed):
    from reportlab.lib.pagesizes import letter
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
    from reportlab.lib.styles import getSampleStyleSheet
    from io import BytesIO

    def generate_pdf(conversation) -> bytes:
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        story = []
        # ... build story list with Paragraphs ...
        doc.build(story)
        return buffer.getvalue()

  OPTION B — weasyprint (renders HTML → PDF, easier to style):
    from weasyprint import HTML

    def generate_pdf(conversation) -> bytes:
        html_content = build_html(conversation)  # write an HTML template
        return HTML(string=html_content).write_pdf()

  RECOMMENDATION: Use weasyprint if the team knows HTML/CSS.
    It's much easier to make it look polished (just write HTML).
    Already declared as an optional extra — install with: uv sync --extra pdf-html

═══════════════════════════════════════════════════════════════
  FUNCTION SIGNATURE (do not change — called from conversations.py)
═══════════════════════════════════════════════════════════════

  def generate_pdf(conversation) -> bytes:
      # conversation is a Conversation ORM object (models/models.py)
      # conversation.intake_summary   → dict (case info)
      # conversation.research_result  → dict (opinion, score, actions, lawyers)
      # conversation.title             → str
      # conversation.created_at        → datetime
      # Returns: raw PDF bytes

TEAM — EFFORT ESTIMATE: 1-2 hours.
  Ask ChatGPT: "Write a generate_pdf function using reportlab that
  takes a Conversation ORM object with intake_summary and research_result
  dict fields, and generates a professional legal report PDF. Return bytes."
  Then show it this docstring.
"""

# ── TODO: implement generate_pdf() ───────────────────────────────────────────


def generate_pdf(conversation) -> bytes:
    """
    Generate a PDF report for a completed conversation.

    Args:
        conversation: Conversation ORM object from models/models.py
                      Must have research_result populated (state = "completed")

    Returns:
        bytes: Raw PDF file content. Returned directly by the API endpoint.

    Raises:
        NotImplementedError: Until implemented by the team.
    """
    # TODO: implement using reportlab or weasyprint — see docstring above
    raise NotImplementedError(
        "generate_pdf() not yet implemented. "
        "See utils/pdf_export.py docstring for implementation guide."
    )
